# Generated by Django 5.0.7 on 2024-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'продвижение', 'verbose_name_plural': 'продвижения'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='name',
            new_name='promotion_name',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='name',
            new_name='tariff_name',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tariffs',
            field=models.ManyToManyField(related_name='promotions', to='product.tariff', verbose_name='Тариф'),
        ),
    ]
